### ISSUE TITLE
[BUG?] RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by BlossomiShymae** [DarkIntaqt/lolassethelper#3]
**Describe the bug**
After running the script to generate static assets, python becomes angy and spams the terminal with said error in the title.

**To Reproduce**
1. Follow `SETUP.md`.
2. Use the default value for `translateChallenges`.
3. Run the script.
4. Receive duplicate errors after challenges are finished without translation.

**Expected behavior**
Script to complete without error.

**Error**
```bash
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001D3BBA1F160>
Traceback (most recent call last):
  File "C:\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
This error was repeated a lotsies. ( ´•̥×•̥` )

**Environment:**
 - Windows 10
 - Python 3.8.3
 
 **Notes**
 It might be platform-specific to Windows according to this [StackOverflow question](https://stackoverflow.com/questions/61543406/asyncio-run-runtimeerror-event-loop-is-closed).

**Comment by DarkIntaqt** [comment]
Oh. I wasn't aware of this issue, as I never tested the script on Windows 10 tbh. Thanks for reporting it ^^

**Comment by DarkIntaqt** [comment]
Closed, reopen if that ever should appear again ^^
